VocalPodcastProject/vocal

CMakeLists.txt
Updated in pkg_check_modules as webkit2gtk-4.0 is used in DEPS_PACKAGES.
Otherwise the build fails on Arch Linux.
=> Update dependency to webkit2gtk-4.0

src/Objects/Episode.vala
Like I already posted on g+
> Does this code work for you?
I was trying to steal it, but it turns out "time.year" is "Years since 1900" and "time.month" is "Months since January – [0, 11]" while DateTime counts from 1-12.
So I did:
"new GLib.DateTime.local(1900 + time.year, 1 + time.month, time.day, time.hour, time.minute, time.second);"
see date issues in #80
=> fix episode dates

po/vocal.pot, src/Widgets/SettingsDialog.vala
Just a random fix: all the labels in the "preferences" dialog box had a colon at the end except this one.
=> missing colon in the "preferences" dialog box

src/Utils/Utils.vala
Now using regex to remove HTML tags and special sequences. Also taking into account special characters such as tab and new lines to avoid bad printings such as this one:
=> simplification and improvement of the html_to_markup method

CMakeLists.txt, cmake/Translations.cmake, src/MainWindow.vala, src/Objects/Podcast.vala, src/Vocal.vala, src/Widgets/CoverArt.vala, src/Widgets/DirectoryArt.vala
Avoid to hardcode images path, in order to install Vocal on BSD systems. Second changes respect "standard" location of traduction files (usually ${PREFIX}/share/locale).
=> Don't hardcode images path, and respect standard of installation directories

src/MainWindow.vala, src/Widgets/CloudLoginDialog.vala, src/Widgets/Toolbar.vala
Trivial changes, which replaces the 'xdg-open' utility by Gtk.show_uri () function.
=> Replace 'xdg-open' utility by Gtk.show_uri () function

src/Widgets/DownloadDetailBox.vala
Made details_box use markup, rather than display formatting tags as plaintext.
=> Let details_box use markup

src/Utils/Utils.vala
I believe this will address the segfault issue I reported in issue #196 .
=> Check return value of Glib.Uri.unescape_string for null value.

src/MainWindow.vala
This commit should fix issue #201 .
When setting the message of a `Gtk.MessageDialog` in the constructor a [`printf`](https://valadoc.org/glib-2.0/GLib.FileStream.printf.html) style format string is expected. If the text contains certain '%' style format escapes with no values an error occurs. 
~~This commit works around this issue by using the `set_markup()` method instead, which expects a "Pango" markup string instead.~~ * see below
=> Fix crash when unsubscribing from feeds with certain format chars in title.

src/Utils/Utils.vala
Minor fixes to `html_to_markup`. 
1. Fix anchor regex to match cases where anchor text contains newlines.
2. Fix inconsistent 'a' tag escaping.
=> Minor fixes to anchors/links in html-to-markup conversion.

CMakeLists.txt
Now it installs into `/usr/share/metainfo` which is the correct folder for `*.appdata.xml` files.
=> Made the *.appdata.xml file install into the correct folder now

src/Widgets/PodcastView.vala, src/Widgets/QueuePopover.vala
These are minor fixes, but very helpful when attempting to debug other issues with `G_DEBUG=fatal-criticals`. Fixes the following error messages:
* `[FATAL 10:20:46.276264] [Gtk] gtk_container_remove: assertion 'GTK_IS_WIDGET (widget)' failed`
Don't attempt to remove the `episodes` queue list in `QueuePopover.vala` when null (during initial creation).
* `[FATAL 10:34:48.041190] [Gtk] gtk_container_remove: assertion 'GTK_IS_WIDGET (widget)' failed`
Don't attempt to remove null `scrolled` from PodcastView
=> Minor Gtk error fixes.

src/Objects/Episode.vala, src/Objects/Podcast.vala
If certain string elements were not parsed from the source feed the
properties on the Episode and Podcast object would remain null, sometimes
causing `string_replace: assertion 'self != NULL' failed` errors.
This commit simply initializes these properties as empty strings.
=> Fix misc. null errors on Episode and Podcast string properties.

README.md
Use the .flatpakref file rather than having to first add the .flatpakrepo and then installing from it.
This also matches the instructions given to users on Flathub.
=> Switch Flatpak instructions to one command

CMakeLists.txt, data/com.github.needle-and-thread.vocal.gresource.xml, src/Objects/Podcast.vala, src/Utils/FeedParser.vala, src/Widgets/CoverArt.vala, src/Widgets/DirectoryArt.vala, src/Widgets/SearchResultBox.vala
If this is accepted, I'm not sure how the existing `//usr/share/vocal/vocal-missing.png` and `//usr/share/vocal/banner.png` will be removed or whether they even need to be removed after an update.
#167 #143
=> GResource for vocal-missing.png and banner.png

CMakeLists.txt, src/Controller.vala, src/Library.vala, src/MainWindow.vala, src/Services/ImageCache.vala, src/Utils/FeedParser.vala, src/Utils/SoupClient.vala, src/Utils/Utils.vala, src/Utils/XmlUtils.vala, src/Utils/iTunesProvider.vala, src/Widgets/DirectoryArt.vala, src/Widgets/DirectoryView.vala, src/Widgets/DownloadDetailBox.vala, src/Widgets/SearchResultBox.vala
- Add XmlUtils. For cleaning up xml before parsing it with libxml. eg removing characters that come after closing `</rss>` tag which causes libxml to fail to parse the file when the xml is otherwise valid.
- Add SoupClient. Wrapper for Soup.Session that checks the response code and makes sure vocal doesn't randomly crash because of soup errors. eg if a url string doesn't start with http or https.
- More logging so bugs are easier to find.  eg
`[WARNING 18:34:49.596531] FeedParser.vala:296: Failed to get podcast. Service http://feeds.soundcloud.com/users/soundcloud:users:279952541/sounds.rss returned HTTP status code 404 Not Found`
- Show detailed error when some podcasts fail during import. I've tested this with [this opml file](https://gist.github.com/xpaulnim/6f7567269f7ab8ed62fd3a0d3c2f …
=> Attempt to fix some libxml and libsoup bugs. Better logging.

src/Widgets/PodcastView.vala
Remove unnecessary call to `GLib.Uri.escape_string` on podcast description, which may return null for some otherwise valid text.
Fixes the following error:
[FATAL ...] string_replace: assertion 'self != NULL' failed
=> Fix 'string_replace' null error.

src/Library.vala
To find an episode in vocal, currently you have yo search for the exact title of the episode. This PR makes it such that vocal returns all episodes that have the key word searched for in their title. Example follows.
Before this change, if I had a podcast with these episodes:
When I searched for episodes with the string "LIVE episodes", expecting the two at the top, I got back nothing.
After this change, I get back the episodes:
=> Improve episode search in vocal by using using sql wildcards.

src/Widgets/SearchResultsView.vala
This is related to my other PR #290. When vocal finds the episodes matching the query, the parent podcast might not exist. So the parent.coverart_uri cannot be retrieved because parent is null so vocal crashes.
I think when deleting old episodes, episodes with no parent should also be removed. That would make this kind of thing less likely.
=> Check that parent is not null before creating search results box

src/Widgets/SearchResultsView.vala
I'm using  `grab_focus_without_selecting()` to add focus to `search_entry` when search button in the header bar is clicked and the search pane is shown (https://valadoc.org/gtk+-3.0/Gtk.Entry.grab_focus_without_selecting.html). To select existing text in the entry, `grab_focus()` may also be used (if that gives better UX). Read on grab_focus here https://valadoc.org/gtk+-3.0/Gtk.Widget.grab_focus.html
=> Added search entry autofocus to SearchResultsView.vala

src/Objects/Episode.vala, src/Widgets/NewEpisodesView.vala
This commit uses a `GLib.ListStore` to keep the episodes for the "new episodes"
view, sorting the episodes as they're added.
Addresses issue #295
=> Sort new episodes view by "released date".

src/Widgets/NewEpisodesView.vala
This change causes the UI updates to happen in the main thread instead of the background thread that fetches updates. Already displayed UI elements should not be updated outside of the main thread.
This should fix one of the causes of crashing being reported.
=> Ensure updates to the "new episode" UI happen in the main thread.

src/config.vala
The expected format is `Component/Component-Version`.
Spaces separate multiple components. Current string parsed as `vocal` and `2.3.0` as two distinct components and not Vocal version 2.3.0.
=> Fix HTTP User-Agent string format

src/Widgets/PodcastView.vala
The `download_all` button first gets added to the toolbar. A later attempt to pack the
same button widget to the "actions_box" fails and causes the following error:
`[Gtk] gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed`
This removes the second attempt to pack the download all button.
=> Fix "parent not null error" when adding `download_all` button a second time.

src/Library.vala
The name search sql was missing the 'LIKE' wildcard characters (%)
in the search, resulting in no matches.
=> Fix podcast name search.

src/Objects/Podcast.vala
The following changes were necessary to correctly handle covers in the main library view.
Check local_art_uri against empty string.
Switch around File.new_for_path/File.new_for_uri for local_art and remote_art.
Correctly detect https:// urls as remote_art_uri.
=> Fixed missing covers in local library view (Fixes #268)

src/Objects/Podcast.vala
Since #375 was merged, podcast cover art does not display. This change
`GLib.File.new_for_uri` for both `remote_art_uri` and `local_art_uri`
and consolidates the getter logic to eliminate null and empty check
inconsistencies. The core of this issue appears to be the the use of
`new_for_path`, which expects an absolute or relative filepath rather
than a `file://` URI.
=> Fix coverart property getter logic

src/Controller.vala, src/MainWindow.vala
The infobar is engineered to be all-purpose for delivering update messages to the user. For now though, it just shows up when episode updates are starting / stopping.
=> Added an infobar which now gets displayed when updates are underway.

src/Library.vala
Vocal currently crashes if the remote art request fails with a
non-success HTTP status code. This change fixes that and allows the
application to fall back to the missing artwork icon.
Fixes #406.
=> Fix crash on missing remote podcast artwork

src/Utils/SoupClient.vala
Fix for #405
Reading the response stream line by line resulted in responses being built incorrectly. For instance the following
```
xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
xmlns:rawvoice="http://www.rawvoice.com/rawvoiceRssModule/"
```
resulted in `xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"xmlns:rawvoice="http:/` because there is no space added between the two attributes.
=> Read response body data as text rather than stream in request_as_string.

src/Widgets/PodcastView.vala
The bug mentioned in #399 only occurred when the episodes were sorted as new. The reason for that was because when the podcasts were populated, the `boxes` array always stored the episodes from older to newer, while `listbox` stored them based on `controller.settings.newest_episodes_first`, causing them to be inverted, meaning that when the episodes were sorted as new, if the first one was marked as played, the icon changed on the last item of the list.
My solution was to `insert` the episodes to `boxes` also using `controller.settings.newest_episodes_first`.
I'm not sure if this is the most efficient way of doing. Let me know if I did anything wrong!
=> Fixed bug where the mark as played icon isn't cleared

src/Widgets/Toolbar.vala
A quick fix where a line of code was repeated twice accidentally, which overwrote the relief style change after the first initialization.
=> Fixes volume button relief style

src/Utils/MPRIS.vala, src/Widgets/EpisodeDetailBox.vala
Though minor, these errors cause gdb to break when running with `G_DEBUG=fatal-criticals` which is very annoying when debugging other issues.
This commit fixes the following errors:
* Fix fatal `[Gtk] gtk_widget_set_no_show_all: assertion 'GTK_IS_WIDGET
(widget)' failed`  message, don't call `set_no_show_all()` on
null `download_button`.
* `[GLib] ' (sa{sv}as)' is not a valid GVariant format string`
=> Fix minor errors with null download button and invalid GVariant format string.

CMakeLists.txt, tests/CMakeLists.txt, tests/TestCase.vala, tests/TestPodcast.vala, tests/test_main.vala
This PR adds a basic unit test runner adapted from the [vala-cmake-example](https://github.com/flplv/vala-cmake-example) example project, including a (very) basic Podcast unit test example.
This should make it easier to identify bugs and test solutions for future code.
=> Feature: add test runner

src/Controller.vala, src/Library.vala, src/MainWindow.vala, src/Objects/Episode.vala, src/Objects/Podcast.vala, src/Utils/FeedParser.vala, src/Widgets/SearchResultsView.vala
This is a simplified version of #379 as a result of the discussion on that PR thread.
This PR primarily updates the database schema to use the podcast uri to uniquely identify podcasts and the podcast uri and episode guid to uniquely identify episodes, addressing the problem identified in #320 
This change also uses the existing export/import methods to migrate existing subscriptions. Note that this does not copy episode data directly, which could appear to result in loss of episodes no longer shown in their feeds . Note that the actual episode data is retained so technically recovery is possible though complex (as in the #379 example).
This is a minimized changeset, and should be a work in progress.
=> Update database schema & primary keys.

src/Utils/FeedParser.vala
Currently Vocal uses the first image it can find as the thumbnail. I've seen some Podcasts where the first image is just a low resolution image, while the iTunes image has a much higher resolution(e.g. [Destination Linux Podcast](https://destinationlinux.org/feed/mp3/)). With this commit Vocal will use the iTunes image - if there is one - otherwise it will still use the first image of the feed.
=> Use iTunes image if available

src/Utils/Utils.vala
Currently get error messages like 
(com.github.needleandthread.vocal:68386): Gtk-WARNING **: 13:19:28.220: Failed to set text 'CNN Chief Medical Correspondent Dr. Sanjay Gupta talks to healthcare providers on the frontlines in New Rochelle, a New York suburb where a large cluster of cases prompted Governor Andrew Cuomo to set up a containment zone and deploy the National Guard. <a href="http://knit.audio/podcast-advertising"&gt;via Knit</a>' from markup due to error parsing markup: Error on line 1 char 318: “&gt;via” is not a valid name.
This fixes that. The first '>' does not get picked up and gets converted to &gt; currently.
=> Fix regex to properly ignore <a href tags

INSTALL
Vocal will crash when trying to add a Podcast if gvfs isn't installed, because it fails when downloading the Podcast image. This affects mostly Arch users, because on most other distros gvfs is preinstalled.
I've already reported this in the Arch Linux bug tracker, so they'll hopefully add the dependency as well.
Fixes [#388 ](https://github.com/needle-and-thread/vocal/issues/388)
=> Add gvfs to dependency list

src/Controller.vala, src/MainWindow.vala
The first commit enables the use of markup in the infobar, so when adding a Podcast the URL will be bold(previously it just showed `<b>URL</b>`).
The second commit hides the infobar automatically after the Podcast has been added successfully.
=> Infobar improvements when adding a podcast

data/com.github.needle-and-thread.vocal.desktop, src/Vocal.vala
These minor changes allows other apps, like my Odysseus web browser, to handle webfeed discovery. Thereby avoiding requiring people to find, copy, and paste links.
The one thing in this pull request (which I hope won't remain so) which is Odysseus-specific is the `X-WebFeed-Type` key I added to Vocal's .desktop file. This currently says Vocal should be offered for subscribing to webfeeds containing attachments of any type elementary Music and Videos supports.
=> Add integration point for other apps to provide feed discovery

src/Utils/Utils.vala
Resolves #494 by escaping the value of href before passing returning it. Compare screenshot below to the one in the Issue.
=> Clean up a tag hrefs before returning markup.

data/com.github.needleandthread.vocal.appdata.xml
This is needed for appstream-generator to find the associated desktop file.
See also:
- https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable
- https://github.com/ximion/appstream-generator/issues/88
=> Add launchable tag to appdata

src/Controller.vala, src/MainWindow.vala
This commit sets the setting `dark_mode_enabled` to true when launching Vocal for the first time, if the user has the setting `gtk-application-prefer-dark-theme` enabled globally. 
This also fixes two issues when the global dark theme setting is enabled, but the `dark_mode_enabled` setting from Vocal is set to false:
- Dark application + light headerbar (only when using Elementary theme)
- the application thinks it is light (at startup) even when it's not(it shows the "Use Dark Theme" entry in the dropdown menu, even though it's already dark)
=> Respect global dark theme preference

src/Objects/Episode.vala
The RSS spec states that pubdates should be formatted according to RFC
822, but podcast feeds don't always conform to that (see episode three
of [Conversations in Code] for an example). Currently, if Vocal
encounters a pubdate of any other format, it crashes. To prevent that,
this change does two things:
1. Adds support for parsing multiple datetime formats. Only two formats
are supported initially. A more robust implementation would include
many common formats seen across podcast feeds.
2. Sets the default pubdate to the current time. This is not an ideal
solution, but it prevents the application from crashing.
[Conversations in Code]: https://conversationsincode.xyz/rss/podcast.xml
=> Support multiple datetime formats for episode pubdate

src/Utils/FeedParser.vala, src/Widgets/DirectoryArt.vala
This fixes the non-existent Podcast description in the search results view when clicking on the Info button.
Fixes: #415
=> Show podcast description on info button (Search)

src/Vocal.vala
Otherwise the build fails with
```
/build/source/src/Vocal.vala:65.50-68.9: error: value is less accessible than constant `Vocal.VocalApp.app_options'
65 |         public const OptionEntry[] app_options = {
|                                                  ^
66 |             { "hidden", 'h', 0, OptionArg.NONE, out Option.OPEN_HIDDEN, "Open without displaying the window so podcasts will continue to update", null },
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
67 |             { null }
| ~~~~~~~~~~~~~~~~~~~~
68 |         };
| ~~~~~~~~~ 
Command-line option `--thread` is deprecated and will be ignored
Compilation failed: 1 error(s), 0 warning(s)
ninja: build stopped: subcommand …
```
=> Fix build with vala 0.56
