- CMakeLists.txt
> Revert "Update dependency to webkit2gtk-4.0"

- src/MainWindow.vala
> Stop handled events from bubbling up

- CMakeLists.txt
- src/Objects/Podcast.vala
- src/Services/ImageCache.vala
- src/Widgets/CoverArt.vala
- src/Widgets/DirectoryArt.vala
- src/Widgets/DirectoryView.vala
- src/Widgets/SearchResultBox.vala
- src/Widgets/SearchResultsPopover.vala
- src/config.vala.cmake
Album art is cached is library_path/.cache 
all files are cached as png and are named by the hash of their url which makes it easier to lookup.
> Cache album art

- src/MainWindow.vala
It basically adds the Noise behavior where if you close the window while it's playing, it will hide it instead of either minimizing or quiting the app :smiley:
> Hide instead of iconify

- CMakeLists.txt
- src/Services/ImageCache.vala
- src/Utils/FeedParser.vala
- src/Utils/Utils.vala
- src/Utils/iTunesProvider.vala
- src/config.vala
- src/config.vala.cmake
Using a user-agent seems to be required by some remote servers.
Solves issue #27.
> http requests are now using a user-agent

- src/Widgets/DownloadDetailBox.vala
Reverts needle-and-thread/vocal#151
> Revert "Let details_box use markup"

- src/Library.vala
- src/MainWindow.vala
- src/Utils/Utils.vala
- src/Widgets/QueuePopover.vala
- src/Widgets/QueueRow.vala
Uses drag and drop to make updating the queue a bit faster. Also, makes it such that the queue doesn't contain duplicates. #187
> Use drag and drop in queue list.

- src/Library.vala
> Use parametrized query for search term.

- src/Widgets/PlaybackBox.vala
> Use fixed width progress bar.

- src/Utils/FeedParser.vala
- src/Widgets/EpisodeDetailBox.vala
Use episode summary if found and no episode description is found. Also, condense repeated whitespace when building label for episode description.
> Use episode summary if no description found, condense whitespace in description label.

- data/com.github.needle-and-thread.vocal.desktop
Looks like something got fucky
> Fix US translation

- src/MainWindow.vala
- src/Services/ImageCache.vala
- src/Utils/MPRIS.vala
- src/Widgets/CoverArt.vala
These error messages are pretty minor on their own but make debugging with `G_DEBUG` difficult. Also, not having them clutter up the terminal will make it easier to read more critical messages.
I've made the changes discrete in case you'd prefer to cherry pick from them.
> Fixes misc console errors.

- src/MainWindow.vala
> Skip already downloaded podcasts when download all is clicked

- src/Library.vala
- src/Objects/Podcast.vala
Just clearing up code that is used in more than one place in Library.vala
> Move duplicate Episode and Podcast from row code to method.

- src/Services/ImageCache.vala
- src/Utils/SoupClient.vala
In my last PR, I should have removed the assertions in SoupClient. Also when merging from master, I should have changed `from_stream_async` to `from_stream` since `get_image` is now async.
> Cant use async method in async

- src/Widgets/PodcastView.vala
> Add selected episodes to queue from podcastView.

- src/Widgets/PodcastView.vala
I am an idiot. #300 Thankfully we've got Houston CI coming to save everyone from my carelessness.
> Misspelling

- src/Widgets/DirectoryArt.vala
This should fix the crash reported in issue #315
> Check for null string return value in podcast summary

- src/MainWindow.vala
> Remove extra percent

- src/Library.vala
> Added some logic to detect podcast feeds that are being added to prevent crashing by repeatedly pressing the add button.

- src/Utils/FeedParser.vala
- src/Utils/XmlUtils.vala
I have implemented atom support to resolve issue #357
> Adding atom support

- src/Widgets/PlaybackBox.vala
> Use the scrollwheel to scan the currently playing episode.

- src/Utils/SoupClient.vala
> Thrown error should be GLib.Error.

- src/Vocal.vala
It's 2019!
Signed-off-by: Sid-Sun <sid-sun@outlook.com>
> Update app years for 2019.

- com.github.needleandthread.vocal.gschema.xml
- src/MainWindow.vala
- src/VocalSettings.vala
- src/Widgets/SettingsDialog.vala
> Added an option to keep Vocal from playing in the background when closed

- README.md
This adds the steps to build the package from source on Debian based systems.
> update README with build steps

- src/Widgets/SettingsDialog.vala
This improves accessibility by assigning the corresponding labels to their switches and buttons.
> Settings dialog: use proper mnemonics

- src/MainWindow.vala
Vocal crashes when attempting to play episodes. This change fixes that.
> Fix null pointer exception when setting artwork

- data/com.github.needleandthread.vocal.appdata.xml
This PR adds custom XML lines for AppCenter support.
> update appcenter data
